Repository CARMIN-org/CARMIN-API, pull requests merged in 2018-04, with the labels that each got.

#95 Small enhancements
  carmin.yaml
Labels: bug, enhancement

#98 Merge master back in develop
  README.md
  carmin.yaml
Labels: bug

#83 Describes pipelines in the Boutiques format
  carmin.yaml
Labels: enhancement
